services:
  cesium-viewer:
    build:
      context: .
      dockerfile: Dockerfile
    image: cesium-viewer:latest
    ports:
      - "8000:80"
    volumes:
      - ${POINTCLOUD_TILES_PATH}:/3dTilesPointCloud
      - ${POINTCLOUD_ASSETS_PATH}:/PointCloud_assets
      - ./src/config/nginx.conf:/etc/nginx/nginx.conf
      - ./src/page:/usr/share/nginx/html
    environment:
      - NGINX_PORT=80
    restart: unless-stopped