version: "3.8"

services:
    cesium-viewer:
        image: python:3.9-alpine
        container_name: cesium
        ports:
            - "8080:8000"
        volumes:
            - .:/app:ro
        working_dir: /app
        command: python -m http.server 8000
        restart: unless-stopped
