services:
  cesium-viewer:
    build:
      context: .
      dockerfile: Dockerfile
    image: cesium-viewer:latest
    ports:
      - "8000:80"
    volumes:
      - ${POINTCLOUD_TILES}:/3dTilesPointCloud
      - ${POINTCLOUD_PY3D_ASSETS}:/PointCloud_py3d_assets
      - ${SEGMENTATION_ASSETS}:/segmentation

      - ./src/config/nginx.conf:/etc/nginx/nginx.conf
      - ./src/page:/usr/share/nginx/html
    environment:
      - NGINX_PORT=80
    restart: unless-stopped
