version: "3.8"

services:
  cesium-viewer:
    build:
      context: ./src
    image: cesium-viewer:latest
    ports:
      - "8000:80"
    volumes:
      - ./src:/app
      - ${POINTCLOUD_ASSETS_PATH}:/assets
      - ${TILES_PATH}:/3dTiles
      - ./3dTilesTexturing:/3dTilesTexturing
    command: ./entrypoint.sh
    restart: unless-stopped
