FROM nginx:alpine

WORKDIR /app

# COPY page/ /usr/share/nginx/html/

COPY nginx.conf /etc/nginx/nginx.conf
# RUN apk update && apk add pv coreutils

# RUN mkdir -p /3dTiles
# RUN mkdir -p /3dTilesTexturing

EXPOSE 80
